[package]
name = "incremental_affix"
version = "0.1.0"
edition = "2024"
resolver = "2"

[dependencies]
anymap = "0.12.1"
bevy = { version = "0.17.2", features = ["experimental_bevy_ui_widgets", "bevy_dev_tools", "bevy_ui_debug"] }
rand = "0.9.2"